services:
  minio:
    image: minio/minio
    container_name: minio
    hostname: minio
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioroomily
      MINIO_ROOT_PASSWORD: miniopassword
    volumes:
      - ./minio/data:/data
    command: server --console-address ':9001' /data
    networks:
      - shared_net:
  postgresdb:
    image: postgres
    container_name: postgresdb
    hostname: postgresdb
    restart: always
    ports:
      - 5432:5432
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - POSTGRES_PASSWORD=roomily
      - POSTGRES_DB=roomily
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      shared_net: