services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - /var/lib/redis/data:/data
    environment:
      - REDIS_USERNAME=root
      - REDIS_PASSWORD=roomily
      - REDIS_PORT=6379
  minio:
    image: minio/minio
    container_name: minio
    hostname: minio
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=roomily
      - MINIO_ROOT_PASSWORD=miniopassword
      - VIRTUAL_HOST=minio.mrthinkj.site
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=minio.mrthinkj.site
      - LETSENCRYPT_EMAIL=blog@minio.mrthinkj.site
    volumes:
      - /var/lib/minio/data:/data
    command: server --console-address ':9001' /data
    networks:
      - pi_shared_net
  postgresdb:
    image: postgres
    container_name: postgresdb
    hostname: postgresdb
    restart: always
    ports:
      - 5432:5432
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - POSTGRES_PASSWORD=28122003
      - POSTGRES_DB=roomily
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - pi_shared_net
networks:
  pi_shared_net:
    external: true
