services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - /var/lib/redis/data:/data
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - REDIS_PORT=6379
    networks:
      - pi_shared_net
  minio:
    image: minio/minio
    container_name: minio
    hostname: minio
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - MINIO_ROOT_USER=roomily
      - MINIO_ROOT_PASSWORD=miniopassword
      - VIRTUAL_HOST=storage.roomily.tech
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=storage.roomily.tech
      - LETSENCRYPT_EMAIL=blog@storage.roomily.tech
    volumes:
      - /var/lib/minio/data:/data
    command: server --console-address ':9001' /data
    networks:
      - pi_shared_net
  postgresdb:
    image: postgres
    container_name: postgresdb
    hostname: postgresdb
    restart: always
    ports:
      - 5432:5432
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - POSTGRES_PASSWORD=28122003
      - POSTGRES_DB=roomily
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - pi_shared_net
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - RABBITMQ_DEFAULT_USER=roomily
      - RABBITMQ_DEFAULT_PASS=roomily
      - VIRTUAL_HOST=mb.roomily.tech
      - VIRTUAL_PORT=5672
      - LETSENCRYPT_HOST=mb.roomily.tech
      - LETSENCRYPT_EMAIL=blog@storage.roomily.tech
    volumes:
      - /var/lib/rabbitmq/data:/var/lib/rabbitmq/data
    networks:
      - pi_shared_net
networks:
  pi_shared_net:
    external: true
