package com.c2se.roomily.enums;

public enum NotificationType {
    CHAT,
    NEW_BILL,
    NEW_COMMENT,
    NEW_REPORT,
    SUBSCRIPTION_EXPIRY,
    SUBSCRIPTION_REMINDER,
    FIND_PARTNER_POST_DELETED,
    ROOM_EXPIRED,
    DEBT_EXPIRED,
    DEPOSIT_NOT_PAID,
    SUBSCRIPTION,
    RENTAL_UPDATE,
    RENTAL_CANCELLED,
    DEPOSIT_REFUNDED,
    PAYMENT_FAILED
}
