spring:
  application:
    name: Roomily
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST:postgresdb}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DB:roomily}
    username: ${POSTGRESQL_USER:postgres}
    password: ${POSTGRESQL_PASSWORD:28122003}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  threads:
    virtual:
      enabled: true
redis:
  host: redis
  port: 6379
app:
  jwt:
    secret: b1ae877ce7cd4e8a5fbd1615b1bd1780057c0774d0cb26adafadabde66e33fb0
    expiration: 604800000
  resource:
    static-location: resources/static
minio:
  access-key: roomily
  secret-key: miniopassword
  url: ${MINIO_URL:https://storage.roomily.tech}
  bucket:
    image: images
    contract: contracts
rabbitmq:
  host: rabbitmq
  port: 5672
  username: roomily
  password: roomily
payos:
  client-id: bb08d5f8-72bf-425a-a13b-b39c52d91ca7
  api-key: 73c759f5-eaf2-41f1-90cb-9bbd9385e7ec
  checksum-key: abcc7cfc44ba34141ec1db246ba44362638268b22d7df8ee4efd8f7c753cacdc
springdoc:
  api-docs:
    path: /api-docs
management:
  endpoints:
    web:
      exposure:
        include: "*"
google:
  map:
    api-key: AIzaSyDefn6P99CBXAKfA_nE2J-6zIh4NKrpCgw
  firebase:
    api-key: YOUR_FIREBASE_API_KEY